ENH Use SearchableMultiDropdownField
silverstripe/silverstripe-siteconfig pull request #149
Opened 2023-11-29 01:10 UTC by emteknetnz

Issue https://github.com/silverstripe/developer-docs/pull/412

2023-12-04 22:07 UTC, GuySartorelli requested changes
Don't forget to remove the `$membersMap` variable assignment

2023-12-08 03:27 UTC, emteknetnz commented
Have removed $membersMap variable

2023-12-11 22:00 UTC, GuySartorelli requested changes
LGTM, but needs a dependency bump for admin and framework.

2023-12-12 21:40 UTC, emteknetnz commented
Have updated composer.json

2023-12-13 00:47 UTC, GuySartorelli approved these changes
LGTM, will merge when admin and framework PRs have been merged.

2023-12-14 20:33 UTC, GuySartorelli commented
This is failing CI

2023-12-14 22:32 UTC, emteknetnz commented
Have updated behat test, though will require this new PR to be merged first - https://github.com/silverstripe/silverstripe-admin/pull/1635

2023-12-17 23:49 UTC, GuySartorelli requested changes
Passes locally but need to remove debug steps

2023-12-17 23:49 UTC, GuySartorelli commented on tests/behat/features/manage-page-permissions.feature
> +@sboyd
```suggestion
```

2023-12-17 23:49 UTC, GuySartorelli commented on tests/behat/features/manage-page-permissions.feature
> +    Given I take a screenshot after every step
```suggestion
```

2023-12-18 21:04 UTC, emteknetnz commented on tests/behat/features/manage-page-permissions.feature
> +@sboyd
Removed

2023-12-18 21:04 UTC, emteknetnz commented on tests/behat/features/manage-page-permissions.feature
> +    Given I take a screenshot after every step
Removed

2023-12-18 21:40 UTC, GuySartorelli approved these changes
LGTM

2023-12-18 21:40 UTC, merged